export const dataList = [
  {
    id: 1,
    name: "Chloe Han",
    skill1: "BA",
    level1: "Sr",
    skill2: "PO",
    level2: "Ps",
    department: "Takumi",
    domain: "BA",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Sophia",
  },
  {
    id: 2,
    name: "Akio Marita",
    skill1: "Java",
    level1: "Md",
    skill2: "PM",
    level2: "Jr",
    department: "DU12",
    domain: "Java",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Chibi",
  },

  {
    id: 3,
    name: "Rusia",
    skill1: "BA",
    level1: "Ps",
    skill2: "Brse",
    level2: "Md",
    department: "Takumi",
    domain: "BA",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Key",
  },
  {
    id: 4,
    name: "Hanna",
    skill1: "Test",
    level1: "Jr",
    skill2: "BA",
    level2: "Fs",
    department: "Takumi",
    domain: "Test",
    Study_point: "458",
    Work_status: "Active",
    Alisa: "Rosie",
  },
  {
    id: 5,
    name: "Marry",
    skill1: "BA",
    level1: "Md",
    skill2: "Design",
    level2: "Jr",
    department: "Takumi",
    domain: "BA",
    Study_point: "572",
    Work_status: "Active",
    Alisa: "Bella",
  },

  {
    id: 6,
    name: "Helen",
    skill1: "Design",
    level1: "Sr",
    skill2: "BA",
    level2: "Fs",
    department: "Takumi",
    domain: "Design",
    Study_point: "555",
    Work_status: "Active",
    Alisa: "Han",
  },
  {
    id: 7,
    name: "Akio Marita",
    skill1: "Java",
    level1: "Ex",
    skill2: "PM",
    level2: "Jr",
    department: "DU12",
    domain: "Java",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Chibi",
  },
  {
    id: 8,
    name: "Rusia",
    skill1: "BA",
    level1: "Ps",
    skill2: "PO",
    level2: "Fs",
    department: "Takumi",
    domain: "BA",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Key",
  },
  {
    id: 9,
    name: "Akio Marita",
    skill1: "Java",
    level1: "Sr",
    skill2: "PA",
    level2: "Ex",
    department: "DU12",
    domain: "Java",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Chibi",
  },
  {
    id: 10,
    name: "Rusia",
    skill1: "BA",
    level1: "Sr",
    skill2: "PM",
    level2: "Ps",
    department: "Takumi",
    domain: "BA",
    Study_point: "540",
    Work_status: "Active",
    Alisa: "Key",
  },
];
